FROM python:3.10.11-slim-buster

ENV PYTHONUNBUFFERED 1

RUN apt update && apt install -y entr

RUN apt-get clean && apt-get autoremove

COPY /requirements/base.txt base.txt
RUN pip install -r base.txt

COPY ./ /code/
WORKDIR /code/src/winterfell_bot

CMD ["python", "app.py"]